### ISSUE TITLE
Decompress context properties

### ISSUE THREAD

**Issue by ngruson** [PeterLindgren-se/biztalk-get-suspended-messages-sql#1]
Hi @PeterLindgren-se ,

I've been using this repo to import suspended messages into a custom SQL database for reporting purposes.
Very helpful :).

Now, I'm also looking to import context properties of those messages. So I have changed the SQL script slightly to include the `imgPropbag` column from the `Parts` table.
I also changed the `biztalk-get-suspended-messages.ps1` script to write the context properties to disk.

When decompressing the context properties from disk, `biztalk-decompress-message.exe` throws an exception:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from H
RESULT: 0x8000FFFF (E_UNEXPECTED))
   at Microsoft.BizTalk.Message.Interop.CompressionStreams.DecompressSequentialStream(Stream rawStream, Stream& compressedStream, UInt32& bytesRead, UInt32& bytesWritten)
   at Microsoft.BizTalk.Message.Interop.CompressionStreams.Decompress(Stream stm)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[]
 namedParams)
   at MyClass.DecompressFile(String inputFilename, String outputFilename, Type compressionStreamsType)
   at MyClass.Main(String[] args)
```

So apparently, the decompression code can't be used to decompress the context properties. Maybe the serialization format is different.
Do you happen to know how I can get the contents of the context properties?

Thank you!

**Comment by PeterLindgren-se** [comment]
Hi @ngruson, thanks for your feedback!
The Parts.imgPropBag contains some other property bag, I'm not sure exactly which. The message context properties are stored in the spool.imgContext column. It is not compressed, it is the serialized IBaseMessageContext inmsg.Context. I haven't looked deeper into it than that, I found some old code that might point you in the right direction.
To extract the data, add these lines to the SQL and PS files, respectively:
```
	   ,DATALENGTH(s.imgContext) as [DatalengthContext]
	   ,s.imgContext
```
```
  # Write imgContext
  $fileName = "$baseFileName$fragmentNamePart.context"
  $bytesToWrite = $_.DatalengthContext
  Write-Output "Writing imgContext $bytesToWrite bytes to $fileName"
  [System.IO.File]::WriteAllBytes("$folderName\$fileName", $_.imgContext[0..($bytesToWrite-1)])
```
Links for inspiration (looks like you might need .Net code and not Powershell):

https://biztalkmessages.wordpress.com/2009/05/13/unleashing-the-spool-table-well-at-least-partly/
https://maximelabelle.wordpress.com/2009/12/10/serializing-message-context-and-part-properties/

Please let me know if and how you managed to deserialize the context properties. Once you've managed to deserialize, it's up to you how you want to display and use the properties.

**Comment by PeterLindgren-se** [comment]
@ngruson I've updated the code to download and save the message context. I've also added sample code that read a message context file and dump the content in human-readable form on the console, you should be good to go from there to adapt the code to suit your needs.

**Comment by ngruson** [comment]
Thanks for including this 👍!
I will have a look after my holidays.
